### ISSUE TITLE
Using LazySets as a backend

### ISSUE THREAD

**Issue by mforets** [arlk/ConvexBodyProximityQueries.jl#8]
Hi,
Very nice library! :tada: I'm one of the lead developers of [LazySets.jl](https://github.com/JuliaReach/LazySets.jl) and it was amusing to know that:

```julia
import ConvexBodyProximityQueries.support
using LazySets

function ConvexBodyProximityQueries.support(obj::LazySet{N}, dir::SVector{D, N}) where {D, N}
    return LazySets.support_vector(dir, obj) |> SVector{D, N}
end
```
Works well with your generic implementation. This permits any [lazy set representation](https://juliareach.github.io/LazySets.jl/dev/#Library-Outline-1) to be used (those are ~40 set representations and operations that can be combined concretely or lazily) -- if this can be of interest to some, i don't know yet ;).

The following benchmarks follow those from the README:

### Small number of vertices

```julia
using StaticArrays

polyA = @SMatrix rand(2, 8)
polyB = @SMatrix(rand(2, 8)) .+ 1.5
dir = @SVector(rand(2)) .- 0.5

@btime closest_points($polyA, $polyB, $dir)
@btime minimum_distance($polyA, $polyB, $dir)
@btime tolerance_verification($polyA, $polyB, $dir, $1.0)
@btime collision_detection($polyA, $polyB, $dir)

  145.811 ns (0 allocations: 0 bytes)
  131.983 ns (0 allocations: 0 bytes)
  125.578 ns (0 allocations: 0 bytes)
  125.269 ns (0 allocations: 0 bytes)

A = VPolygon([polyA[:, i] for i in 1:size(polyA, 2)])
B = VPolygon([polyB[:, i] for i in 1:size(polyB, 2)])

@btime closest_points($A, $B, $dir)
@btime minimum_distance($A, $B, $dir)
@btime tolerance_verification($A, $B, $dir, $1.0)
@btime collision_detection($A, $B, $dir)

  107.575 ns (0 allocations: 0 bytes)
  85.338 ns (0 allocations: 0 bytes)
  78.242 ns (0 allocations: 0 bytes)
  76.779 ns (0 allocations: 0 bytes)
```

### Large number of  vertices

```julia
polyA = @SMatrix rand(2, 100)
polyB = @SMatrix(rand(2, 100)) .+ 1.5
dir = @SVector(rand(2)) .- 0.5;

@btime closest_points($polyA, $polyB, $dir)
@btime minimum_distance($polyA, $polyB, $dir)
@btime tolerance_verification($polyA, $polyB, $dir, $1.0)
@btime collision_detection($polyA, $polyB, $dir)

  1.933 μs (0 allocations: 0 bytes)
  1.932 μs (0 allocations: 0 bytes)
  1.426 μs (0 allocations: 0 bytes)
  1.421 μs (0 allocations: 0 bytes)

A = VPolygon([polyA[:, i] for i in 1:size(polyA, 2)])
B = VPolygon([polyB[:, i] for i in 1:size(polyB, 2)])
​
@btime closest_points($A, $B, $dir)
@btime minimum_distance($A, $B, $dir)
@btime tolerance_verification($A, $B, $dir, $1.0)
@btime collision_detection($A, $B, $dir)

  367.424 ns (0 allocations: 0 bytes)
  340.771 ns (0 allocations: 0 bytes)
  240.108 ns (0 allocations: 0 bytes)
  241.198 ns (0 allocations: 0 bytes)
```

**Comment by arlk** [comment]
Oh wow, this is very interesting indeed. The performance boost is quite remarkable. 

I think anyone working in motion planning would definitely be interested in better representations for their obstacles vs the representation as a collection of unordered vertices I had setup. Another thing I can think of is if they had moving objects I see that LazySets already has them [covered](https://juliareach.github.io/LazySets.jl/dev/lib/lazy_operations/Translation/#def_Translation-1). Given, that LazySets supports most representations for convex sets, I think its definitely worth it to change the backend to LazySets and simplify the code-base.

I will have some time at the end of this month to look at how we can integrate this. Thanks for bringing this up! :)

**Comment by mforets** [comment]
> Oh wow, this is very interesting indeed. 

Good to hear, thanks!

> I think its definitely worth it to change the backend to LazySets and simplify the code-base.

One possibility is to add LazySets as an *optional* dependency, so this library still remains light-weight. We do this a lot, using [Requires](https://github.com/JuliaPackaging/Requires.jl). I can send a PR...

**Comment by arlk** [comment]
Thanks! That will be helpful. I think the code deserves some refactoring as well, so I will get working on that.

**Comment by arlk** [comment]
I included some [tests](https://github.com/arlk/ConvexBodyProximityQueries.jl/blob/master/test/lazysets.jl) and it seems to work great! Thanks for adding it in as an optional backend.

**Comment by mforets** [comment]
Glad to know that you found this useful :tada:

**Comment by mforets** [comment]
Just one note: i've seen that one gets most speed if the lazy sets are represented with static vectors for their centers / vector of vectors, etc.

So one can do eg. [here](https://github.com/arlk/ConvexBodyProximityQueries.jl/blob/master/test/lazysets.jl#L11)

```julia
julia> b1 = Ball1(zeros(2), 1.0) 
Ball1{Float64,Array{Float64,1}}([0.0, 0.0], 1.0)

julia> b1 = Ball1(@SVector(zeros(2)), 1.0) # use static array for the center
Ball1{Float64,SArray{Tuple{2},Float64,1,2}}([0.0, 0.0], 1.0)
```

**Comment by arlk** [comment]
That's good to know. I'll update the readme.

**Comment by mforets** [comment]
To easily create random polygons with static vectors as vertices, `VPolygon(@SMatrix(rand(2, 10)))` can be used. For the next LazySets release i'll add a similar constructor for polytopes in vertex representation (https://github.com/JuliaReach/LazySets.jl/issues/2002).

**Comment by arlk** [comment]
Awesome!
But, welp, we cannot have static array Ellipsoids until [this](https://github.com/JuliaArrays/StaticArrays.jl/issues/373) issue is solved on the StaticArrays side.

**Comment by mforets** [comment]
Good catch. In this case from the LazySets side we can add a flag to the constructor to make the check optional; this will be available in the next release `Ellipsoid(c, M, check_posdef=false)`...

 We could otherwise write a fallback `_isposdef` for static matrices (that just checks `isposdef(Matrix(M))`), but `StaticArrays` is not a dependency of LazySets.. it could be made optional though..
